[package]

name = "queryst"
version = "1.0.0"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
description = "Rust query string parser with nesting support"
repository = "https://github.com/rustless/queryst"
keywords = ["json", "web", "url", "parser"]
license = "MIT"

[dependencies]
serde = "0.7"
serde_json = "0.7"
url = "1"
regex = "0.1"
lazy_static = "0.2"
